### ISSUE TITLE
Allow dokuwiki release to be selected or uploaded

### ISSUE THREAD

**Issue by Harvie** [splitbrain/dokuwiki-plugin-upgrade#118]
I think it might be usefull to have advanced menu with these features:

1.) manualy upload custom zipball to be used (so i can upload upgrade to dokuwiki without internet access)
2.) allow to select any brach or tag from https://github.com/splitbrain/dokuwiki using dropdown menu
3.) allow to provide custom url of git repository or zipball to be used

These will be probably useful even for developers to test different versions. As well as for regular users doing upgrade/downgrade.

**Comment by splitbrain** [comment]
If you have no internet access, I think a manual upgrade is your better choice anyway. I wouldn't want to add more complexity for a use case that is probably less than 1% of users of the upgrade plugin.

Regarding allowing other releases than the stable one I'm not sure it's a good idea. Downgrading is not really supported by the plugin as it wouldn't know what files to remove. It would probably work, but it would leave cruft behind... OTOH it would open possibilities for novice users to mess up, accidentally installing the wrong version.

Anyway this tool is not for developers. If you're a developer you should be using git. Checking out arbitrary branches and tags is simple then.

**Comment by Harvie** [comment]
> Downgrading is not really supported by the plugin as it wouldn't know what files to remove.

Well that would obviously get fixed later when you will again upgrade to current version :-)

**Comment by Tuxdiver** [comment]
Currently, the upgrade plugin only allows installation of the RC "Hogfather", but not the hotfix for Greebo

**Comment by leeyc0** [comment]
Actually I am having same problem. Because of plugin incompatibility we are stuck to Greebo forever. (We used syntax plugins extensively therefore removing old plugins requires extensive revamp and loss of functionality).

**Comment by dregad** [comment]
It would be really great, like in today's situation when a new stable release is available (Igor) and a hotfix release is published also on old-stable (Hogfather 2020-07-29a), if the plugin allowed selection of which release to install.

I cannot yet upgrade to Igor due to plugin incompatibilities that need to be resolved, and it would be very nice to have the comfort of using the plugin instead of having to perform a manual upgrade.

I don't really care much about the other options or scenarios outlined by the OP. As @splitbrain said, those are mostly covered by using Git. But the above scenario is a common case likely to be faced by end-users.

**Comment by splitbrain** [comment]
won't implement
