### ISSUE TITLE
Choosing languages

### ISSUE THREAD

**Issue by riksoft** [splitbrain/dokuwiki-plugin-upgrade#55]
This is not a bug but could be a very nice and handy option: having the choice to take into account only one or more languages dropping all the others.

I mean: My wiki use only english because the contents are in english and I find it useless to load tons of languages just to localize the menus.

At the moment I use https://github.com/Taggic/langdelete after the upgrade to delete all but english.
The option of choosing the language could save a lot of traffic (especially for dokuwiki.org).

See ya!

**Comment by splitbrain** [comment]
Fixing this would not result in reduced traffic, because we download a zip from github. When implemented, it would simply not extract the unwanted language files.

When implementing, I would not allow for fine tuned selection of languages but give two choices:

* extract all languages
* extract current languages only

**Comment by splitbrain** [comment]
won't implement. if someone submits a PR, I'll reconsider.
