### ISSUE TITLE
Files assigned to user 'apache'

### ISSUE THREAD

**Issue by sushidave** [splitbrain/dokuwiki-plugin-upgrade#99]
After upgrading a DokuWiki installation on an Apache server by the upgrade plugin to Detritus, errors appeared on some pages of the backend, e.g.:

Writing /var/www/vhosts/example.com/httpdocs/data/meta/archiv.meta failed
Unable to save metadata file. Hint: disk full, file permissions, safe mode setting.

IMHO the plugin did not show any errors or warnings during the upgrade process.
 
After the upgrade CHMOD these files was not possible and the file manager showed that they were assigned to user "apache" and to the server's group. The server admin (hosting company) was able to reassign it back to the correct user - which solved the issue for now, but we probably would run into the same issue at the next upgrade.

The admin said that user 'apache' was assigned because the files were uploaded via CMS instead of FTP. He recommended to create an FTP user in the CMS - if possible - that uploads the files. Does the plugin provide such a thing?

How can you use the plugin and avoid this issue?

**Comment by splitbrain** [comment]
All files created from within PHP code are owned by the user the process is running under. All your pages for example will be created with the same user. Your host seems to run one PHP process for everyone hosted on the server instead of having separate PHP processes for each user (through FPM). This is quite ugly, but there's nothing I can do about it. It's definitely not a problem of the upgrade plugin. The workaround suggested by your hoster is even more ugly.

**Comment by sushidave** [comment]
Thank you for your help.

I forgot to mention that the installation is in a shared hosting environment which seems to be the reason that there is only one PHP process for all users. Is the plugin applicable for installations on dedicated servers only?

**Comment by splitbrain** [comment]
The plugin works just fine for shared hosting.
